# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KMLive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 4.0.1'
    pod 'Kingfisher', '~> 3.1.1'
    pod 'YYModel'
    pod 'SVProgressHUD'
  target 'KMLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KMLiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
